"""initial schema

Revision ID: 20ba22d4f737
Revises:
Create Date: 2026-09-15 15:04:09.833183

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20ba22d4f737"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "provider", "patient", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_users_id_tenant_id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_id_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "confirmed",
                "cancelled",
                "completed",
                "no_show",
                name="appointment_status",
            ),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scheduled_end > scheduled_start",
            name=op.f("ck_appointments_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id", "tenant_id"],
            ["users.id", "users.tenant_id"],
            name="fk_appointments_patient_users",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id", "tenant_id"],
            ["users.id", "users.tenant_id"],
            name="fk_appointments_provider_users",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_appointments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_index(
        "ix_appointments_tenant_id_patient_id",
        "appointments",
        ["tenant_id", "patient_id"],
        unique=False,
    )
    op.create_index(
        "ix_appointments_tenant_id_provider_id_scheduled_start",
        "appointments",
        ["tenant_id", "provider_id", "scheduled_start"],
        unique=False,
    )
    op.create_index(
        "ix_appointments_tenant_id_scheduled_start",
        "appointments",
        ["tenant_id", "scheduled_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_appointments_tenant_id_scheduled_start", table_name="appointments")
    op.drop_index(
        "ix_appointments_tenant_id_provider_id_scheduled_start", table_name="appointments"
    )
    op.drop_index("ix_appointments_tenant_id_patient_id", table_name="appointments")
    op.drop_table("appointments")
    # drop_table leaves the Postgres ENUM type behind; without this an
    # upgrade after a downgrade fails with "type already exists".
    sa.Enum(name="appointment_status").drop(op.get_bind(), checkfirst=False)
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=False)
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
